export const DATA = {
  countKey: [14, 15, 13, 14, 10],
  0: [
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  1: [
    ["button", "button-num", "btn-backspace"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  2: [
    ["button", "button-num", "btn-backspace", "btn-caps"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  3: [
    ["button", "button-num", "btn-backspace", "btn-shift"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "btn-const"],
    ["button", "btn-const", "btn-shift"],
  ],
  4: [
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num"],
    ["button", "button-num", "btn-space"],
    ["button", "button-num"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "btn-const"],
    ["button", "btn-const"],
    ["button", "btn-const"],
  ],
};

export const KEYS_EN = {
  0: [
    ["~", "`"],
    ["!", "1"],
    ["@", "2"],
    ["#", "3"],
    ["$", "4"],
    ["%", "5"],
    ["^", "6"],
    ["&", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
    "Backspace",
  ],
  1: [
    "Tab",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    ["{", "["],
    ["}", "]"],
    ["|", "\\"],
    "DEL",
  ],
  2: [
    "Caps Lock",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    [":", ";"],
    ['"', "'"],
    "ENTER",
  ],
  3: [
    "Shift",
    "\\",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
    ["<", ","],
    [">", "."],
    ["?", "/"],
    "▲",
    "Shift",
  ],
  4: ["Ctrl", "", "Win", "Alt", "", "Alt", "Ctrl", "◀", "▼", "▶"],
};

export const KEYS_RU = {
  numbers: [
    ["!", "1"],
    ['"', "2"],
    ["№", "3"],
    [";", "4"],
    ["%", "5"],
    [":", "6"],
    ["?", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
  ],
  1: ["й", "ц", "у", "к", "е", "н", "г", "ш", "щ", "з", "х", "ъ", ["/", "\\"]],
  2: ["ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э"],
  3: ["я", "ч", "с", "м", "и", "т", "ь", "б", "ю", [",", "."]],
};

export const KEYS = {
  //en - ru - en/shift - ru/shift
  0: [
    ["`", "ё", "~", "Ё"],
    ["1", "1", "!", "!"],
    ["2", "2", "@", '"'],
    ["3", "3", "#", "№"],
    ["4", "4", "$", ";"],
    ["5", "5", "%", "%"],
    ["6", "6", "^", ":"],
    ["7", "7", "&", "?"],
    ["8", "8", "*", "*"],
    ["9", "9", "(", "("],
    ["0", "0", ")", ")"],
    ["-", "-", "_", "_"],
    ["=", "=", "+", "+"],
    "Backspace",
  ],
  1: [
    "Tab",
    ["q", "й"],
    ["w", "ц"],
    ["e", "у"],
    ["r", "к"],
    ["t", "е"],
    ["y", "н"],
    ["u", "г"],
    ["i", "ш"],
    ["o", "щ"],
    ["p", "з"],
    ["[", "х", "{", "Х"],
    ["]", "ъ", "}", "Ъ"],
    ["\\", "\\", "|", "/"],
    "DEL",
  ],
  2: [
    "Caps Lock",
    ["a", "ф"],
    ["s", "ы"],
    ["d", "в"],
    ["f", "а"],
    ["g", "п"],
    ["h", "р"],
    ["j", "о"],
    ["k", "л"],
    ["l", "д"],
    [";", "ж", ":", "Ж"],
    ["'", "э", '"', "Э"],
    "ENTER",
  ],
  3: [
    "Shift",
    ["\\", "\\", "|", "/"],
    ["z", "я"],
    ["x", "ч"],
    ["c", "с"],
    ["v", "м"],
    ["b", "и"],
    ["n", "т"],
    ["m", "ь"],
    [",", "б", "<", "Б"],
    [".", "ю", ">", "Ю"],
    ["/", ".", "?", ","],
    "▲",
    "Shift",
  ],
  4: ["Ctrl", "", "Win", "Alt", "", "Alt", "Ctrl", "◀", "▼", "▶"],
};

const keyCode = {
  192: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  48: "",
  189: "",
  187: "",

  81: "",
  87: "",
  69: "",
  82: "",
  84: "",
  89: "",
  85: "",
  73: "",
  79: "",
  80: "",
  219: "",
  221: "",
  220: "",

  65: "",
  83: "",
  68: "",
  70: "",
  71: "",
  72: "",
  74: "",
  75: "",
  76: "",
  186: "",
  222: "",

  226: "",
  90: "",
  88: "",
  67: "",
  86: "",
  66: "",
  78: "",
  77: "",
  188: "",
  190: "",
  191: "",
};
