export const DATA = {
  countKey: [14, 15, 13, 14, 9],
  0: [
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  1: [
    ["button", "button-num", "btn-backspace"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  2: [
    ["button", "button-num", "btn-backspace"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num", "btn-backspace"],
  ],
  3: [
    ["button", "button-num", "btn-backspace"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "button-num"],
    ["button", "btn-const"],
    ["button", "btn-const"],
  ],
  4: [
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "button-num", "btn-space"],
    ["button", "button-num"],
    ["button", "button-num", "btn-ctrl"],
    ["button", "btn-const"],
    ["button", "btn-const"],
    ["button", "btn-const"],
  ],
};

export const KEYS_EN = {
  0: [
    ["~", "`"],
    ["!", "1"],
    ["@", "2"],
    ["#", "3"],
    ["$", "4"],
    ["%", "5"],
    ["^", "6"],
    ["&", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
    "Backspace",
  ],
  1: [
    "Tab",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    ["{", "["],
    ["}", "]"],
    ["|", "\\"],
    "DEL",
  ],
  2: [
    "Caps Lock",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    [":", ";"],
    ['"', "'"],
    "ENTER",
  ],
  3: [
    "Shift",
    "\\",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
    ["<", ","],
    [">", "."],
    ["?", "/"],
    "▲",
    "Shift",
  ],
  4: ["Ctrl", "Win", "Alt", "", "Alt", "Ctrl", "◀", "▼", "▶"],
};

export const KEYS_RU = {
  numbers: [
    ["!", "1"],
    ['"', "2"],
    ["№", "3"],
    [";", "4"],
    ["%", "5"],
    [":", "6"],
    ["?", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
  ],
  1: ["й", "ц", "у", "к", "е", "н", "г", "ш", "щ", "з", "х", "ъ", ["/", "\\"]],
  2: ["ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э"],
  3: ["я", "ч", "с", "м", "и", "т", "ь", "б", "ю", [",", "."]],
};
