export const DATA = {
  countKey: [14, 15, 13, 14, 8],
  0: [
    ["button", "button-num", "code-192"],
    ["button", "button-num", "code-49"],
    ["button", "button-num", "code-50"],
    ["button", "button-num", "code-51"],
    ["button", "button-num", "code-52"],
    ["button", "button-num", "code-53"],
    ["button", "button-num", "code-54"],
    ["button", "button-num", "code-55"],
    ["button", "button-num", "code-56"],
    ["button", "button-num", "code-57"],
    ["button", "button-num", "code-48"],
    ["button", "button-num", "code-189"],
    ["button", "button-num", "code-187"],
    ["button", "btn-backspace", "code-8"],
  ],
  1: [
    ["button", "btn-backspace", "code-9"],
    ["button", "button-num", "code-81"],
    ["button", "button-num", "code-87"],
    ["button", "button-num", "code-69"],
    ["button", "button-num", "code-82"],
    ["button", "button-num", "code-84"],
    ["button", "button-num", "code-89"],
    ["button", "button-num", "code-85"],
    ["button", "button-num", "code-73"],
    ["button", "button-num", "code-79"],
    ["button", "button-num", "code-80"],
    ["button", "button-num", "code-219"],
    ["button", "button-num", "code-221"],
    ["button", "button-num", "code-220"],
    ["button", "btn-backspace", "code-46"],
  ],
  2: [
    ["button", "btn-caps", "code-20"],
    ["button", "button-num", "code-65"],
    ["button", "button-num", "code-83"],
    ["button", "button-num", "code-68"],
    ["button", "button-num", "code-70"],
    ["button", "button-num", "code-71"],
    ["button", "button-num", "code-72"],
    ["button", "button-num", "code-74"],
    ["button", "button-num", "code-75"],
    ["button", "button-num", "code-76"],
    ["button", "button-num", "code-186"],
    ["button", "button-num", "code-222"],
    ["button", "btn-backspace", "code-13"],
  ],
  3: [
    ["button", "btn-shift", "code-16"],
    ["button", "button-num", "code-226"],
    ["button", "button-num", "code-90"],
    ["button", "button-num", "code-88"],
    ["button", "button-num", "code-67"],
    ["button", "button-num", "code-86"],
    ["button", "button-num", "code-66"],
    ["button", "button-num", "code-78"],
    ["button", "button-num", "code-77"],
    ["button", "button-num", "code-188"],
    ["button", "button-num", "code-190"],
    ["button", "button-num", "code-191"],
    ["button", "btn-const", "code-38"],
    ["button", "btn-const", "btn-shift", "code-16"],
  ],
  4: [
    ["button", "btn-ctrl", "code-17"],
    ["button", "btn-alt", "code-18"],
    ["button", "btn-space", "code-32"],
    ["button", "btn-alt", "code-18"],
    ["button", "btn-ctrl", "code-17"],
    ["button", "btn-const", "code-37"],
    ["button", "btn-const", "code-40"],
    ["button", "btn-const", "code-39"],
  ],
};

export const KEYS_EN = {
  0: [
    ["~", "`"],
    ["!", "1"],
    ["@", "2"],
    ["#", "3"],
    ["$", "4"],
    ["%", "5"],
    ["^", "6"],
    ["&", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
    "Backspace",
  ],
  1: [
    "Tab",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    ["{", "["],
    ["}", "]"],
    ["|", "\\"],
    "DEL",
  ],
  2: [
    "Caps Lock",
    "a",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    [":", ";"],
    ['"', "'"],
    "ENTER",
  ],
  3: [
    "Shift",
    "\\",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
    ["<", ","],
    [">", "."],
    ["?", "/"],
    "▲",
    "Shift",
  ],
  4: ["Ctrl", "Alt", "", "Alt", "Ctrl", "◀", "▼", "▶"],
};

export const KEYS_RU = {
  numbers: [
    ["!", "1"],
    ['"', "2"],
    ["№", "3"],
    [";", "4"],
    ["%", "5"],
    [":", "6"],
    ["?", "7"],
    ["*", "8"],
    ["(", "9"],
    [")", "0"],
    ["_", "-"],
    ["+", "="],
  ],
  1: ["й", "ц", "у", "к", "е", "н", "г", "ш", "щ", "з", "х", "ъ", ["/", "\\"]],
  2: ["ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э"],
  3: ["я", "ч", "с", "м", "и", "т", "ь", "б", "ю", [",", "."]],
};

export const KEYS = {
  //en - ru - en/shift - ru/shift
  0: [
    ["`", "ё", "~", "Ё"],
    ["1", "1", "!", "!"],
    ["2", "2", "@", '"'],
    ["3", "3", "#", "№"],
    ["4", "4", "$", ";"],
    ["5", "5", "%", "%"],
    ["6", "6", "^", ":"],
    ["7", "7", "&", "?"],
    ["8", "8", "*", "*"],
    ["9", "9", "(", "("],
    ["0", "0", ")", ")"],
    ["-", "-", "_", "_"],
    ["=", "=", "+", "+"],
    "Backspace",
  ],
  1: [
    "Tab",
    ["q", "й"],
    ["w", "ц"],
    ["e", "у"],
    ["r", "к"],
    ["t", "е"],
    ["y", "н"],
    ["u", "г"],
    ["i", "ш"],
    ["o", "щ"],
    ["p", "з"],
    ["[", "х", "{", "Х"],
    ["]", "ъ", "}", "Ъ"],
    ["\\", "\\", "|", "/"],
    "DEL",
  ],
  2: [
    "Caps Lock",
    ["a", "ф"],
    ["s", "ы"],
    ["d", "в"],
    ["f", "а"],
    ["g", "п"],
    ["h", "р"],
    ["j", "о"],
    ["k", "л"],
    ["l", "д"],
    [";", "ж", ":", "Ж"],
    ["'", "э", '"', "Э"],
    "ENTER",
  ],
  3: [
    "Shift",
    ["\\", "\\", "|", "/"],
    ["z", "я"],
    ["x", "ч"],
    ["c", "с"],
    ["v", "м"],
    ["b", "и"],
    ["n", "т"],
    ["m", "ь"],
    [",", "б", "<", "Б"],
    [".", "ю", ">", "Ю"],
    ["/", ".", "?", ","],
    "▲",
    "Shift",
  ],
  4: ["Ctrl", "Alt", "", "Alt", "Ctrl", "◀", "▼", "▶"],
};
